<a href="https://colab.research.google.com/github/ValdazoAmerico/faiss-search/blob/main/faiss_newsearch.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np

In [ ]:
pip install sentence_transformers

     |████████████████████████████████| 85 kB 2.0 MB/s 
     |████████████████████████████████| 2.5 MB 5.0 MB/s 
     |████████████████████████████████| 1.2 MB 18.6 MB/s 
     |████████████████████████████████| 43 kB 1.5 MB/s 
     |████████████████████████████████| 895 kB 18.6 MB/s 
     |████████████████████████████████| 3.3 MB 35.4 MB/s 
  Created wheel for sentence-transformers: filename=sentence_transformers-2.0.0-py3-none-any.whl size=126709 sha256=9b419ba354b70e570240e21002e27aabde7821e5a5bc5b3261742624e5b9bca9
  Stored in directory: /root/.cache/pip/wheels/d1/c1/0f/faafd427f705c4b012274ba60d9a91d75830306811e1355293
Successfully built sentence-transformers


In [ ]:
from sentence_transformers import SentenceTransformer

model_faiss = SentenceTransformer("bert-base-nli-mean-tokens")

In [ ]:
model.encode(['hello world'])

array([[-1.50538713e-01,  5.29025160e-02,  2.08420134e+00,
         1.41297638e-01,  4.38929975e-01,  1.24937445e-01,
         3.32377583e-01,  1.05838096e+00,  6.03558868e-03,
        -8.61336961e-02, -9.99487221e-01,  3.18820477e-01,
        -4.51345928e-03,  5.95006585e-01,  7.58371294e-01,
         1.64414883e-01, -8.48956406e-01, -9.83352885e-02,
        -6.95176199e-02, -3.47868204e-01, -8.61892700e-01,
        -8.10270756e-02, -3.24415594e-01, -1.15120077e+00,
         9.96495932e-02, -7.85229802e-01,  4.35979366e-01,
        -1.60889244e+00, -2.26758748e-01,  9.49694291e-02,
        -4.74193126e-01, -3.08338910e-01,  1.11107028e+00,
        -2.29384094e-01, -5.38672745e-01,  8.46415043e-01,
        -9.40801740e-01,  1.99518144e-01, -2.74196357e-01,
        -1.69324651e-01,  1.96000838e+00, -3.42636377e-01,
         1.46522021e+00,  3.53447348e-01, -9.44688439e-01,
        -3.38534683e-01, -2.87146598e-01,  5.31773686e-01,
        -8.19039568e-02, -1.20050502e+00, -6.74837589e-0

In [ ]:
!pip install faiss

     |████████████████████████████████| 4.7 MB 4.0 MB/s 


In [ ]:
pip install faiss-cpu --no-cache

     |████████████████████████████████| 8.4 MB 3.9 MB/s 


In [ ]:
#IndexFlatL2
import faiss

index = faiss.IndexFlatL2(768)
 

In [ ]:
index.is_trained

True

In [ ]:
array = []
for m in lines:
  a = model.encode([m])
  array.append(a)

In [ ]:
len(lines)

14504

In [ ]:
len(array)

14504

In [ ]:
array2 = np.array(array)

In [ ]:
array2 = array2.reshape(14504, 768)

In [ ]:
index.add(array2)

In [ ]:
index.ntotal

14504

In [ ]:
xq = model.encode(['i want my mamma'])

In [ ]:
k = 4

In [ ]:
%%time
D, I = index.search(xq, k)
print(I)

[[ 5562  4161 12901   727]]
CPU times: user 6.03 ms, sys: 980 µs, total: 7.01 ms
Wall time: 8.89 ms


In [ ]:
[f'{i}: {lines[i]}' for i in I[0]]

["5562: take into one's family.",
 '4161: RT Jones analyst Juli Niemann said Grant was "the one we were all pulling for.',
 '12901: We think they have the right to choose.',
 '727: And now it\'s anything he wants to say," confirmed Stone County Nursing and Rehabilitation Center social director Alesha Badgley.']

In [ ]:
nlist = 50
quantizer = faiss.IndexFlatL2(768)
index = faiss.IndexIVFFlat(quantizer, 768, nlist)

In [ ]:
index.is_trained

False

In [ ]:
index.train(array2)

In [ ]:
index.is_trained

True

In [ ]:
index.add(array2)
index.ntotal

14504

In [ ]:
%%time
D, I = index.search(xq, k)
print(I)

[[ 5562  4161 12901   727]]
CPU times: user 6.83 ms, sys: 14 µs, total: 6.84 ms
Wall time: 16.1 ms


In [ ]:
index.nprobe = 10

In [ ]:
%%time
D, I = index.search(xq, k)
print(I)


[[ 5562  4161 12901   727]]
CPU times: user 5.5 ms, sys: 997 µs, total: 6.5 ms
Wall time: 14.6 ms


In [ ]:
m = 8
bits = 8

quantizer = faiss.IndexFlatL2(768)
index = faiss.IndexIVFPQ(quantizer, 768, nlist, m, bits)

In [ ]:
index.is_trained

True

In [ ]:
index.train(array2)

In [ ]:
index.add(array2)

In [ ]:

D, I = index.search(xq, k)
print(I)

[[14286  2385  3632  6162]]


In [ ]:
[f'{i}: {lines[i]}' for i in I[0]]

['14286: give out, allow to have',
 '2385: legally approve or ratify a person for a position',
 '3632: We intend to appeal vigorously and still expect to be vindicated ultimately.',
 '6162: the act of officially gaining entrance to somewhere']